### ISSUE TITLE
Red PAST

### ISSUE THREAD

**Issue by RinMaru** [SonicFreak94/sadx-dc-lighting#45] opened 2017-03-12 03:30 UTC
Using the latest build of DC Lighting and Mod loader with the DC Conversion Mods.
In Amy's story after beating Hot Shelter the game will bring you to the Past but it will all be in RED Lighting. After exiting the game and going back in the problem is gone. I've been skipping the cutscenes perhaps I tripped something during the transition?

**Comment by supercoolsonic** [comment] 2017-03-14 02:11
I encountered something like this in Sky Deck once. I logged it in one of my lists. PkR though it might be a test palette. Not sure what triggers it, or how to fix it.

**Comment by SonicFreak94** [comment] 2017-03-14 20:42
The lighting is supposed to be generally red with some orange, and it's supposed to have a fading effect. If that's not the case though, then we definitely have a bug on our hands. Also, when you say "latest build", are you referring to the latest development build?

**Comment by Zetchzie** [comment] 2017-03-14 21:26
yea I was using the 1.1.27 build i've run into other errors like the outside of videos (Blacks Bars) turning blue for instance but i think it only happens when skipping them or cutscenes

**Comment by SonicFreak94** [comment] 2017-03-14 21:57
Interesting; I'll take a look when I can. Thanks for the info.

**Comment by SonicFreak94** [comment] 2017-03-23 08:40
I'm unable to reproduce this issue. Can you check that it still happens?

**Comment by Zetchzie** [comment] 2017-03-23 13:20
yea ill run through it again

**Comment by Zetchzie** [comment] 2017-03-23 13:38
This can be closed I was unable to get it again in the latest Release. I think it just randomly bugged that one time.

**Comment by PiKeyAr** [comment] 2017-05-13 03:26
I was able to reproduce this by beating Knuckles' story and then playing through Amy's story until the moment she goes to the Past. I think this happens because something Past fire-related gets stuck after Knuckles' cutscene and doesn't reset when Amy goes there.
The issue only happens if you try to beat multiple character stories without restarting the EXE.

**Comment by PiKeyAr** [comment] 2017-08-09 02:51
Could be related https://twitter.com/shaddytheguy/status/895112143032287233

**Comment by Shaddytheguy** [comment] 2017-08-09 04:34
I don't know what could have triggered this version of what's going on. I updated the lantern engine mod via the loader, and when I saw it was crashing on the character select screen, I grabbed d3d8to9.dll, and it continued to not work. Then, I tried deleting the old copy of the mod and redownloading it off of git, and after replacing d3d8 _again_ it finally worked properly, but after finishing Lost World as Sonic the past had that weird effect where it would fade back into the regular lighting (not on character models though, as you can see). So I really dunno if it's something on my end from a wrong version of the mod or d3d8 (which it could be, I always feel like I have to navigate a labyrinth to download stuff off git). That said, it's convinced me to use DC style water for right now because the neon blue DX water is distracting enough when it's _not_ having weird lighting effects.

I'd already beaten Tails story and gone through Knuckles' opening cutscene, but I'd restarted the exe before this new stuff started happening, and when I did the rest of Knuckles story (halfway through typing this, infact) to see if it happened again, it was [working properly](https://www.youtube.com/watch?v=urQa8ubb2dA). I might add that beforehand, sky deck was bizarrely dark, like it had the Egg Carrier's lighting stuck onto it or something. Unfortunately I wasn't able to get a screen of this, and replaying it in trial mode, it didn't have any such visuals.

**Comment by SonicFreak94** [comment] 2017-08-09 20:28
Hm, strange. I guess this will need some debugging. Thanks for the information. If you manage to narrow it down further of course, let me know!

**Comment by PiKeyAr** [comment] 2017-08-12 18:09
How to reproduce a similar-looking thing: start in Trial mode, go to Sonic's Sky Deck and wait for the palette to change to dark, then exit while it's still dark and start Adventure Mode as Super Sonic. When you go to the Past you'll get this: 
![image](https://user-images.githubusercontent.com/23312549/29243204-d8a9a4dc-7fd4-11e7-832c-43cd2f24fec6.png)

**Comment by SonicFreak94** [comment] 2017-08-12 18:56
It seems as though--as usual--Sky Deck was indirectly the cause of the issue.

I've pushed a change that should address this issue. I'm no longer able to reproduce it with the steps outlined by @PiKeyAr, but it needs testing with the steps described by @Shaddytheguy.

For those able, the build with this change is available [here](https://ci.appveyor.com/project/SonicFreak94/sadx-dc-lighting/build/1.2.58-master/artifacts).

**Comment by SonicFreak94** [comment] 2017-08-12 19:35
Another fix has been pushed to fix the related bug where Sky Deck gets stuck permanently dark. Build available [here](https://ci.appveyor.com/project/SonicFreak94/sadx-dc-lighting/build/artifacts).

_this is all sky deck's fault_

**Comment by RinMaru** [comment] 2017-08-13 01:06
After a recent playthrough today the bug seems to be fixed

**Comment by SonicFreak94** [comment] 2017-08-13 03:58
OK, I'm going to consider this fixed!

**Closed by SonicFreak94** 2017-08-13 03:58 UTC
Labels: bug
