### ISSUE TITLE
it only happen in combination with SA1_Chars mod made by ItsEasyActually

### ISSUE THREAD

**Issue by shadic2001** [SonicFreak94/sadx-dc-lighting#60] opened 2017-08-14 16:39 UTC
#### Encountered behavior
Write a brief description of the bug you encountered here.

#### Expected behavior
Write a brief description of the behavior you expected here.

#### Installed mods

* sadx-input-mod
* sadx-dc-lighting
* ???

#### Steps to reproduce:

1. Steal Burger Shop statue
2. Place him in traffic
3. ???

**Comment by PiKeyAr** [comment] 2017-08-14 17:30
Somebody set up us the bomb?
Please provide a proper description of the issue.

**Comment by RinMaru** [comment] 2017-08-14 22:27
@PiKeyAr  you can close this its not a bug hes talking about the cars going through the statue but it happens with or without the mod

**Comment by SonicFreak94** [comment] 2017-08-14 23:48
no

**Closed by SonicFreak94** 2017-08-14 23:48 UTC
Labels: invalid
